---
# Critical parameters for preprocessing pipeline
preprocessing_parameters:
  SEED: 1234
  MAX_VOCAB_SIZE: 25_000
  BATCH_SIZE: 64
  data_path: data
  train_path: Train.csv
  test_path: Valid.csv
  vectors: glove.6B.100d
  deterministic: True
  tokenizer: spacy
  tokenizer_language: en_core_web_sm

# Critical parameters for model construction
model_parameters:
  EMBEDDING_DIM: 100
  HIDDEN_DIM: 256
  OUTPUT_DIM: 1
  N_LAYERS: 1
  BIDIRECTIONAL: True
  DROPOUT: 0.5
  N_EPOCHS: 20

# Folder and file names
folders:
  results: training_results
  results_filename: results.csv
  model_dict_name: 1_layer_dict.pt
  model_name: 1_layer.pt
  model_dir: model
  chart_dir: charts
  vocab_dir: vocab
  vocab_filename: TEXT
  
# Critical parameters to save progress
prediction_parameters:  
  sentiment_threshold: 0.5